name: Build Develop

on:
  push:
    branches: [ develop ]

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: KtLint
        run: bash ./gradlew ktlintCheck
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Sdk Unit Tests
        run: bash ./gradlew :sdk:testDebugUnitTest --stacktrace 
      - name: App Unit Tests
        run: bash ./gradlew :app:testDebugUnitTest --stacktrace 
      - name: App Instrumented Test
        run: bash ./gradlew :app:assembleDebugAndroidTest --stacktrace
  sdk:
    name: Generate SDK
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build SDK
        run: bash ./gradlew :sdk:assembleDebug --stacktrace
  apk:
    name: Generate APK
    needs: sdk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build APK
        run: bash ./gradlew :app:assembleDebug --stacktrace
